#Filter Configuration
lexik_form_filter:
    force_case_insensitivity: false
    listeners:
        doctrine_orm: true
        doctrine_dbal: false
        doctrine_mongodb: false
    force_case_insensitivity: false
    where_method: ~  # null | and | or
#Pagination Configuration
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template