app:
    resource: "@AppBundle/Controller/"
    type:     annotation
###################################################################################
#  Internationalization
#			http://your-host/app_dev.php/_trans/
###################################################################################
JMSTranslationBundle_ui:
    resource: "@JMSTranslationBundle/Controller/"
    type:     annotation
    prefix:   /_trans